#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


BRANCH=$(git branch --show-current)

if [ "$BRANCH" == "main" ]; then
    flake8
    isort --check-only --profile=black .
    pylint
    pytest --cov=src
    coverage report --fail-under=80
fi
