services:
  scheduler:
    image: ${SLIP}
    hostname: scheduler
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    ports:
      - "8787:8787"
    entrypoint: ["dask","scheduler","--port","8786", "--dashboard-address", ":8787"]

  worker:
    image: ${SLIP}
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    deploy:
      replicas: ${REPLICAS}
    entrypoint: ["dask","worker", "tcp://scheduler:8786"]

  client:
    image: ${SLIP}
    container_name: client
    hostname: client
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://scheduler:8786
    entrypoint: ["/bin/bash"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
