services:
  scheduler:
    image: ${IMAGE}
    hostname: scheduler
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    ports:
      - "8787:8787"
    entrypoint: ["dask","scheduler","--port","8786", "--dashboard-address", ":8787"]

  worker:
    image: ${IMAGE}
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    deploy:
      replicas: ${REPLICAS}
    entrypoint: ["dask","worker", "tcp://scheduler:8786"]

  client:
    image: ${IMAGE}
    container_name: client
    hostname: client
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://scheduler:8786
    entrypoint: ["spectral-line-imaging-pipeline", "run", "--input", "/data/${INPUT}", "--config", "/data/${CONFIG}", "--output", "/data/${OUTPUT_DIR:-output}", "--dask-scheduler", "tcp://scheduler:8786"]
