services:
  scheduler:
    image: ${SLIP}
    hostname: scheduler
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    ports:
      - "8787:8787"
    entrypoint: ["dask","scheduler","--port","8786", "--dashboard-address", ":8787"]

  worker:
    image: ${SLIP}
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    deploy:
      replicas: ${REPLICAS}
    environment:
      REPLICA: "{{.Task.Slot}}"
    entrypoint: [
    "/bin/sh",
    "-c",
    "piper benchmark --command \"dask worker tcp://scheduler:8786\" \
     --output-path /data/benchmark --setup \
     --output-file-prefix $${HOSTNAME}"
    ]

  client:
    image: ${SLIP}
    container_name: client
    hostname: client
    volumes:
      - ${DATA}:/data${MOUNT_FLAGS}
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://scheduler:8786
    entrypoint: ["piper", "benchmark", "--command", "spectral-line-imaging-pipeline run --input ${INPUT} --config ${CONFIG} --output ${OUTPUT} --dask-scheduler tcp://scheduler:8786", "--output-path", "/data/benchmark", "--setup"]
